### ISSUE TITLE
Segmentation fault after retunrning the result

### ISSUE THREAD

**Issue by sbrunner** [mapserver/mapcache#131]
We use MapCache with Memcached using the Apache module.
And with the version 1.4 on Debian Jessie we get a Segmentation fault.

To start to debug the error I try to reproduce the issue on cgi mode and finally I do...

Config File:
```
<?xml version="1.0" encoding="UTF-8"?>
<mapcache>
    <cache name="default" type="memcache">
       <server>
          <host>localhost</host>
          <port>11211</port>
       </server>
    </cache>

   <grid name="swissgrid">
      <size>256 256</size>
      <extent>420000.0 30000.0 900000.0 360000.0</extent>
      <srs>epsg:21781</srs>
      <units>m</units>
      <resolutions>50.0 20.0 10.0 5.0 2.5 2.0 1.5 1.0 0.5 0.25 </resolutions>
      <origin>top-left</origin>
   </grid>

   <source name="plan" type="wms">
      <getmap>
         <params>
            <LAYERS>plan</LAYERS>
            <TRANSPARENT>TRUE</TRANSPARENT>
            <FORMAT>image/png</FORMAT>
         </params>
      </getmap>
      <http>
         <url>http://localhost/sbrunner/mapserv</url>
         <headers>
            <Host>[the host]</Host>
         </headers>
      </http>
   </source>

   <tileset name="plan">
      <source>plan</source>
      <cache>default</cache>
      <grid>swissgrid</grid>
      <metatile>8 8</metatile>
      <metabuffer>0</metabuffer>
      <format>image/png</format>
      <expires>3600</expires> <!-- 1 hour -->
      <auto_expire>13800</auto_expire> <!-- 4 hours -->
      <dimensions>
        <dimension type="values" name="DATE" default="2011">2011</dimension>
      </dimensions>
   </tileset>

   <format name="image/png" type="PNG">
      <compression>fast</compression>
      <colors>256</colors>
   </format>

   <service type="wms" enabled="false"/>
   <service type="wmts" enabled="true"/>
   <service type="tms" enabled="false"/>
   <service type="kml" enabled="false"/>
   <service type="gmaps" enabled="false"/>
   <service type="ve" enabled="false"/>
   <service type="demo" enabled="false"/>

   <errors>report</errors>
</mapcache>
```

Run script:
```
#! /bin/bash
                                                                            
export CONTENT_LENGTH=0
export PATH_INFO=wmts/1.0.0/plan/default/2011/swissgrid/0/0/0.png
export QUERY_STRING=
export SERVER_NAME=nyon-geoportail-testnew.prod.sig.cloud.camptocamp.net
export SERVER_PORT=80
export SERVER_PROTOCOL=HTTP
                                                                                               
export MAPCACHE_CONFIG_FILE=/.../mapcache.xml

/usr/lib/cgi-bin/mapcache
```

And the results I get
================

gdb result:
```
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/cgi-bin/mapcache...(no debugging symbols found)...done.
(gdb) y
Undefined command: "y".  Try "help".
(gdb) r
Starting program: /usr/lib/cgi-bin/mapcache 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Content-Type: image/png
Cache-Control: max-age=11270
Expires: Thu, 01 Oct 2015 11:06:14 GMT
Last-Modified: Thu, 01 Oct 2015 07:16:14 GMT
Content-Length: 145

�PNG
▒

Program received signal SIGSEGV, Segmentation fault.
apr_allocator_destroy (allocator=0x555555778560) at /tmp/buildd/apr-1.5.1/memory/unix/apr_pools.c:150
150     /tmp/buildd/apr-1.5.1/memory/unix/apr_pools.c: No such file or directory.
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) n
Program not restarted.
(gdb) bt
#0  apr_allocator_destroy (allocator=0x555555778560) at /tmp/buildd/apr-1.5.1/memory/unix/apr_pools.c:150
#1  0x00007ffff707cba5 in apr_pool_destroy (pool=<optimized out>) at /tmp/buildd/apr-1.5.1/memory/unix/apr_pools.c:864
#2  0x00007ffff707cbf0 in apr_pool_terminate () at /tmp/buildd/apr-1.5.1/memory/unix/apr_pools.c:639
#3  0x0000555555555a3d in main ()
```

valgrind result:
```
==30790== Memcheck, a memory error detector
==30790== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==30790== Using Valgrind-3.10.0 and LibVEX; rerun with -h for copyright info
==30790== Command: /usr/lib/cgi-bin/mapcache
==30790== 
Content-Type: image/png
Cache-Control: max-age=10648
Expires: Thu, 01 Oct 2015 11:06:14 GMT
Last-Modified: Thu, 01 Oct 2015 07:16:14 GMT
Content-Length: 145

�PNG
▒
==30790== Invalid read of size 4
==30790==    at 0x5998120: apr_allocator_destroy (in /usr/lib/x86_64-linux-gnu/libapr-1.so.0.5.1)
==30790==    by 0x5998BEF: apr_pool_terminate (in /usr/lib/x86_64-linux-gnu/libapr-1.so.0.5.1)
==30790==    by 0x109A3C: main (in /usr/lib/cgi-bin/mapcache)
==30790==  Address 0x4045010 is not stack'd, malloc'd or (recently) free'd
==30790== 
==30790== 
==30790== Process terminating with default action of signal 11 (SIGSEGV)
==30790==  Access not within mapped region at address 0x4045010
==30790==    at 0x5998120: apr_allocator_destroy (in /usr/lib/x86_64-linux-gnu/libapr-1.so.0.5.1)
==30790==    by 0x5998BEF: apr_pool_terminate (in /usr/lib/x86_64-linux-gnu/libapr-1.so.0.5.1)
==30790==    by 0x109A3C: main (in /usr/lib/cgi-bin/mapcache)
==30790==  If you believe this happened as a result of a stack
==30790==  overflow in your program's main thread (unlikely but
==30790==  possible), you can try to increase the size of the
==30790==  main thread stack using the --main-stacksize= flag.
==30790==  The main thread stack size used in this run was 8388608.
 �Om7�@a��TE�z=�tRNS@��f<IDATh��
          ▒0`��
               ▒0`��
                    ▒0`��
                         ▒�▒!m��IEND�B`�==30790== 
==30790== HEAP SUMMARY:
==30790==     in use at exit: 107,228 bytes in 659 blocks
==30790==   total heap usage: 5,396 allocs, 4,737 frees, 395,650 bytes allocated
==30790== 
==30790== LEAK SUMMARY:
==30790==    definitely lost: 32 bytes in 1 blocks
==30790==    indirectly lost: 0 bytes in 0 blocks
==30790==      possibly lost: 0 bytes in 0 blocks
==30790==    still reachable: 107,196 bytes in 658 blocks
==30790==         suppressed: 0 bytes in 0 blocks
==30790== Rerun with --leak-check=full to see details of leaked memory
==30790== 
==30790== For counts of detected and suppressed errors, rerun with: -v
==30790== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
./test: line 24: 30790 Segmentation fault      valgrind /usr/lib/cgi-bin/mapcache
```

**Comment by tbonfort** [comment]
Try using the latest version in branch-1-4 and report back. I've pushed some fixes there and will be preparing a 1.4.1 release soon.

**Comment by sbrunner** [comment]
OK, we bill do it and we will report back :-)

**Comment by sbrunner** [comment]
Thanks, it's working :-)
